#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, Cygwin,
#       Darwin, MinGW, and NonStop.
#
##############################################################################

# Attempt to detect the non-traditional shell we are running under,
# per bug report #1624.
# Standardize on "$_", even though shells like zsh don't fill it in,
# to avoid contaminating the environment with a variable that might
# have significance to the calling shell.
if [ -z "$_" ] ; then
   case $0 in
      */*)
         progname=${0##*/}
         sourcedir=${0%/*}
      ;;
      *)
         case ${PATH-} in
            *:/bin:*|*:/usr/bin:*)
               # We are checking that PATH contains standard directories,
               # which would almost certainly have both "ls" and "which".
               # We are not checking the specific directory names because
               # they vary on different systems.
               if ls -lL /bin/sh >/dev/null 2>&1 &&
                  ls -lL "$(which sh)" >/dev/null 2>&1 ; then
                     sourcedir=$( dirname "$(which sh)" )
               else
                     sourcedir=.
               fi
            ;;
            *)
               sourcedir=.
            ;;
         esac
      ;;
   esac
else
   progname=${_##*/}
   sourcedir=${_##*/}
   sourcedir=${sourcedir%"$progname"}
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For cygwin and MSYS, switch paths to Windows format before running java
if $cygwin || $msys ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)                                       # don't mess with options #(
              *)                                        #(
                 case $arg in                         #(
                   */*)                               #(
                      arg=$( cygpath --path --mixed "$arg" ) ;;
                 esac ;;
            esac
        then
            set -- "$@" "$arg"
        else
            break
        fi
    done
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
#     and any embedded shellness will be escaped.
#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
#     treated as '${Hostname}' itself on the command line.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one argument per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]/#/$'\n'}" &&
#   shift
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process the output from xargs -n1 (one argument per line) to reassemble
# the original arguments, preserving spaces and quotes, taking care to:
#   * preserve backslash characters (using sed to double all backslashes)
#   * escape special characters ($, `, \, newline) in the input to sed
#   * handle arguments that contain literal backslashes
#   * handle arguments that contain literal newlines
#
# The sed script works as follows:
# 1. Double every backslash character (\ becomes \\)
# 2. Escape dollar signs, backticks and newlines with backslashes
# 3. Put quote marks around the entire line
#
# The result is then processed with eval to reconstruct the original arguments.

eval "
   set -- $(
      printf '%s\n' "$ARGS" |
      xargs -n1 |
      sed 's/\\/\\\\/g; s/\$/\\\$/g; s/`/\\`/g; s/^/"/; s/$/"/' |
      tr '\n' ' '
   )" ||
   die "failed to parse command-line arguments"
fi

exec "$JAVACMD" "$@"
